#!/usr/bin/env python3
"""Capture deterministic conformance evidence for the reduced paper-derived comparator."""

from __future__ import annotations

import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "artifact" / "baselines" / "BreakwaterInspired.java"
VALIDATOR = Path(__file__).resolve()

# Independent fixtures transcribed from OSDI 2020 Section 3.2 equations.
# Expected values are literals; they are not generated by the Java implementation.
FIXTURES = [
    {"name": "additive_below_target", "args": ["pool", "100", "2", "5", "0.5", "4", "0.2"], "exit": 0, "stdout": "POOL,2.000000,1.000000,102.000000"},
    {"name": "equal_target_no_decrease", "args": ["pool", "100", "5", "5", "0.5", "4", "0.2"], "exit": 0, "stdout": "POOL,2.000000,1.000000,100.000000"},
    {"name": "proportional_decrease", "args": ["pool", "100", "10", "5", "0.5", "4", "0.2"], "exit": 0, "stdout": "POOL,2.000000,0.800000,80.000000"},
    {"name": "multiplicative_floor", "args": ["pool", "100", "30", "5", "0.5", "4", "0.2"], "exit": 0, "stdout": "POOL,2.000000,0.500000,50.000000"},
    {"name": "issue_to_demand_plus_overcommit", "args": ["client", "100", "80", "4", "15", "5"], "exit": 0, "stdout": "CLIENT,5,20,20,15"},
    {"name": "demand_bound", "args": ["client", "100", "80", "4", "2", "5"], "exit": 0, "stdout": "CLIENT,5,20,7,2"},
    {"name": "single_credit_revocation", "args": ["client", "80", "100", "4", "10", "8"], "exit": 0, "stdout": "CLIENT,1,0,7,-1"},
    {"name": "nonnegative_revocation_deviation", "args": ["client", "80", "100", "4", "0", "0"], "exit": 0, "stdout": "CLIENT,1,0,0,0"},
    {"name": "invalid_target", "args": ["pool", "100", "2", "0", "0.5", "4", "0.2"], "exit": 2, "stderr_prefix": "ERROR,IllegalArgumentException,targetDelay"},
    {"name": "invalid_client_count", "args": ["client", "100", "80", "0", "2", "5"], "exit": 2, "stderr_prefix": "ERROR,IllegalArgumentException,clients"},
    {"name": "invalid_negative_credit", "args": ["client", "100", "-1", "4", "2", "5"], "exit": 2, "stderr_prefix": "ERROR,IllegalArgumentException,credit"},
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def capture(command: list[str]) -> dict:
    proc = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
    return {
        "command": command,
        "exit_code": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: validate_breakwater_inspired.py OUTPUT_DIR", file=sys.stderr)
        return 2
    output_dir = Path(sys.argv[1]).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    java = shutil.which("java")
    if java is None:
        print("java executable not found", file=sys.stderr)
        return 2

    java_version = capture([java, "-version"])
    cases = []
    all_passed = True
    for fixture in FIXTURES:
        command = [java, "--source", "17", "artifact/baselines/BreakwaterInspired.java", *fixture["args"]]
        observed = capture(command)
        passed = observed["exit_code"] == fixture["exit"]
        if "stdout" in fixture:
            passed = passed and observed["stdout"].strip() == fixture["stdout"]
        if "stderr_prefix" in fixture:
            passed = passed and observed["stderr"].strip().startswith(fixture["stderr_prefix"])
        all_passed = all_passed and passed
        cases.append({"fixture": fixture, "observed": observed, "passed": passed})

    evidence = {
        "schema_version": 1,
        "scope": "Breakwater-inspired paper-derived comparator; correctness only",
        "paper_anchors": ["Section 3.2.1 Equations (1)-(2)", "Section 3.2.2 Equations (3)-(6)"],
        "fixture_provenance": "Literal independent expectations transcribed by the validator author from the cited equations; not generated by Java output.",
        "deviations": [
            "Synchronous scalar updates replace distributed server/client messaging and RTT scheduling.",
            "Credit values are integer counts; Equation (4) uses Java integer division.",
            "Equation (6) is clamped at zero to prevent negative unused credits.",
            "No AQM, Shenango queue measurement, demand-piggybacking, expiration, fairness scan, RPC transport, or workload adapter is implemented.",
        ],
        "source_sha256": sha256(SOURCE),
        "validator_sha256": sha256(VALIDATOR),
        "environment": {
            "os": platform.platform(),
            "python": sys.version,
            "java_path": java,
            "java_version": java_version,
            "cpu_count": os.cpu_count(),
        },
        "cases": cases,
        "summary": {"passed": sum(c["passed"] for c in cases), "total": len(cases), "all_passed": all_passed},
    }
    path = output_dir / "validation.json"
    path.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(evidence["summary"], sort_keys=True))
    print(path)
    return 0 if all_passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
